version: '3.8'
services:
  postgres:
    environment:
      POSTGRES_USER: healthadmin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: health_sched_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    environment:
      REDIS_PASSWORD: admin1234
    volumes:
      - ./data/redis:/data
